-- ============================================
-- Seed Default Admin User
-- Creates a default admin user in the database
-- Username: admin
-- Password: Admin123! (can be changed later via UI)
-- ============================================

-- Note: This script uses a BCrypt hash for the password
-- The hash for "Admin123!" is generated by the Auth service
-- If the user doesn't exist, it will be created via the seed script

-- The admin user should be created via the seed-admin-user.ps1 script
-- which uses the Auth Service API to properly hash the password
-- This SQL file is kept for reference but the actual seeding
-- should use the PowerShell script that calls the API

-- Verify admin user exists, if not, it should be created via API registration
-- DO NOT insert password hash directly - use the seed script instead

-- Check if admin user exists
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM auth.users WHERE username = 'admin') THEN
        RAISE NOTICE 'Admin user does not exist. Run seed-admin-user.ps1 to create it.';
    ELSE
        RAISE NOTICE 'Admin user already exists in database.';
    END IF;
END $$;


