name: Browser Service CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Services/Browser/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'
  pull_request:
    paths:
      - 'src/Services/Browser/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore CodingAgent.sln

      - name: Build
        run: dotnet build CodingAgent.sln -c Release --no-restore

      - name: Install Playwright browsers
        run: |
          dotnet build src/Services/Browser/CodingAgent.Services.Browser/CodingAgent.Services.Browser.csproj
          ./src/Services/Browser/CodingAgent.Services.Browser/bin/Debug/net9.0/playwright.sh install --with-deps

      - name: Test (Unit & Integration for Browser Service)
        run: dotnet test src/Services/Browser/CodingAgent.Services.Browser.Tests/CodingAgent.Services.Browser.Tests.csproj --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Conditional Docker build
        if: success()
        run: |
          set -e
          if [ -f src/Services/Browser/CodingAgent.Services.Browser/Dockerfile ]; then
            echo "Dockerfile found. Building image from repository root..."
            REPO=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
            docker build -f src/Services/Browser/CodingAgent.Services.Browser/Dockerfile -t ghcr.io/$REPO/browser:$GITHUB_SHA .
          else
            echo "No Dockerfile found for Browser. Skipping docker build."
          fi
