name: Browser Service CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Services/Browser/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'
  pull_request:
    paths:
      - 'src/Services/Browser/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore CodingAgent.sln

      - name: Build
        run: dotnet build CodingAgent.sln -c Release --no-restore

      - name: Test
        run: dotnet test CodingAgent.sln -c Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Conditional Docker build
        run: |
          set -e
          if [ -f src/Services/Browser/CodingAgent.Services.Browser/Dockerfile ]; then
            echo "Dockerfile found. Building image from repository root..."
            REPO=$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')
            docker build -f src/Services/Browser/CodingAgent.Services.Browser/Dockerfile -t ghcr.io/$REPO/browser:$GITHUB_SHA .
          else
            echo "No Dockerfile found for Browser. Skipping docker build."
          fi
