name: Docs CI

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.github/**'
      - 'docs/**'
  push:
    branches: [ master ]
    paths:
      - '**/*.md'
      - '.github/**'
      - 'docs/**'

jobs:
  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-20-npm-cache
          restore-keys: |
            ${{ runner.os }}-node-20-
      - name: Run markdownlint-cli2
        run: npx -y markdownlint-cli2 "**/*.md" "#node_modules"
        continue-on-error: true

  link-check:
    name: Link Checker
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: lychee-cache-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            lychee-cache-${{ runner.os }}-

      - name: lychee link check
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --base . --no-progress --cache --max-cache-age 1d "**/*.md"
          format: markdown
          output: lychee/out.md
          jobSummary: true
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
          if-no-files-found: warn
