name: Frontend (Angular) CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Frontend/coding-agent-dashboard/**'
      - 'src/Services/Dashboard/**'
      - 'src/Gateway/**'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'src/Frontend/coding-agent-dashboard/**'
      - 'src/Services/Dashboard/**'
      - 'src/Gateway/**'
      - 'package.json'
      - 'package-lock.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      dashboard: ${{ steps.filter.outputs.dashboard }}
      gateway: ${{ steps.filter.outputs.gateway }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'src/Frontend/coding-agent-dashboard/**'
            dashboard:
              - 'src/Services/Dashboard/**'
            gateway:
              - 'src/Gateway/**'

  build-test:
    needs: check-changes
    if: needs.check-changes.outputs.frontend == 'true' || needs.check-changes.outputs.dashboard == 'true' || needs.check-changes.outputs.gateway == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/Frontend/coding-agent-dashboard
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: src/Frontend/coding-agent-dashboard/package-lock.json

      - name: Setup Chrome
        id: setup_chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        env:
          CHROME_BIN: ${{ steps.setup_chrome.outputs.chrome-path }}
        run: npm test -- --watch=false --browsers=ChromeHeadlessCI --code-coverage --no-progress

      - name: Build
        run: npm run build -- --configuration=production
