name: Gateway CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/Gateway/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'
  pull_request:
    paths:
      - 'src/Gateway/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore CodingAgent.sln
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

      - name: Build
        run: dotnet build CodingAgent.sln -c Release --no-restore

      - name: Test
        run: dotnet test CodingAgent.sln -c Release --no-build --logger "trx;LogFileName=test_results.trx"

      - name: Conditional Docker build
        run: |
          set -e
          CTX=""
          if [ -f src/Gateway/CodingAgent.Gateway/Dockerfile ]; then CTX=src/Gateway/CodingAgent.Gateway; fi
          if [ -z "$CTX" ] && [ -f src/Gateway/Dockerfile ]; then CTX=src/Gateway; fi
          if [ -n "$CTX" ]; then
            echo "Dockerfile found in $CTX. Building image..."
            docker build "$CTX" -t ghcr.io/${{ github.repository }}/gateway:${{ github.sha }}
          else
            echo "No Dockerfile found for Gateway. Skipping docker build."
          fi
