name: Gateway CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Gateway/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'
      - '.github/workflows/gateway-ci.yml'
  push:
    branches: [ master ]
    paths:
      - 'src/Gateway/**'
      - 'src/SharedKernel/**'
      - 'CodingAgent.sln'
      - 'Directory.Build.props'
      - 'global.json'
      - '.github/workflows/gateway-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore CodingAgent.sln --force
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
          DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

      - name: Build
        run: dotnet build CodingAgent.sln -c Release --no-restore

      - name: Test Gateway (Unit only)
        run: >-
          dotnet test CodingAgent.sln -c Release --no-build --no-restore
          --filter "Category=Unit&FullyQualifiedName~Gateway"
          --logger "trx;LogFileName=gateway_test_results.trx"
        continue-on-error: true
