name: Gateway CI

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/Gateway/**'
      - '.github/workflows/gateway-ci.yml'
  push:
    branches: [ master ]
    paths:
      - 'src/Gateway/**'
      - '.github/workflows/gateway-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./src/Gateway/CodingAgent.Gateway/CodingAgent.Gateway.csproj

      - name: Build
        run: dotnet build ./src/Gateway/CodingAgent.Gateway/CodingAgent.Gateway.csproj --configuration Release --no-restore

      # Tests to be added when test projects exist
